### ISSUE TITLE
Extend data dictionary to deal with multiple motors – Stint 1

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-firmware-models#54]
When #53 is merged, we need to make the dictionary general enough to contain structures dealing w/ 2 (or even more) motors.

**Comment by pattacini** [comment]
I realized I'm kind of curbing the dev because of my management activities.
@mfussi66, I therefore retarget this task so that you'll be the main assignee whereas I'll be supporting you as sidekick.

**Comment by mfussi66** [comment]
As agreed, we will carefully inspect the Data Dictionary on what data structures are specific for each motor. This way, we can understand which ones need to be "vectorized".

**Comment by mfussi66** [comment]
I focused on the FOC controller block, and identified (at the moment) the IO data structures involved in it. I could not find an automated tool in Simulink that would give me a nice overview of all the variables, so I made a diagram. 
I coloured in green the elements that I think could be considered "motor agnostic", aka could be used regardless of the actuation model.
Instead, you can see in red the components that are motor-specific.
Data structures that contains both motors-specific elements and agnostic ones are coloured with the gradient. 
![arch_model drawio](https://github.com/robotology/icub-firmware-models/assets/38140169/e6238b09-9be3-46b0-a465-cefb9c05c981)

I think all the red components could be used as IO interfaces for our motor controller objects, which can be instanced as reusable models.

**Comment by mfussi66** [comment]
Next, I can check the internals of the FOC controllers to see which specific data structures are used.

**Comment by mfussi66** [comment]
Analyzing the FOC controller it came out that, as it could be imagined, only a very small subset of the data is used, suggesting that the subset be decoupled from the rest and be made its own interface:

![FOC drawio](https://github.com/robotology/icub-firmware-models/assets/38140169/140f4c25-30f6-4c15-b921-5adfe24b2ab7)

**Comment by pattacini** [comment]
Good point 👍🏻

**Comment by mfussi66** [comment]
Similar checks were also done for the outer controller and the estimators:

## Outer control
![outer_en drawio](https://github.com/robotology/icub-firmware-models/assets/38140169/e0efa62d-dd1a-481f-8633-4d3bdf5375db)

## Estimation
![estimation drawio](https://github.com/robotology/icub-firmware-models/assets/38140169/bba3d6f1-b918-42fa-bf90-80ba322b9ec3)

**Comment by mfussi66** [comment]
Speaking with @pattacini, it came out that we could follow two approaches:
1. Refactor the  amcbldc code to make it general enough to support 1 or more instances of an actuator
- **Pros:** 
    - Work on both boards at once
    - Better enforcement of function reusability
 - **Cons:**
    - Two boards to be tested in the same timeframe
    - Necessity to work around the amcbldc specifics (e.g. messaging, not present on the amcfoc)
2. Start with the amcfoc project from scratch and later adapt the amcbldc
- **Pros:** 
    - Starting from scratch can give more freedom
    - Possibly faster iteration time for the amcfoc
    - The amcbldc will be separated so it will still work with its own code
 - **Cons:**
    - Longer total development time (amcbldc will be refactored at a later date)

**Comment by mfussi66** [comment]
> Start with the amcfoc project from scratch and later adapt the amcbldc

At the end of the day, we will follow this route.
This approach will require to rewrite the dictionary, while at the same time trying to keep the IO of the models intact. 
It will be necessary to start small:
- take only the models esplicitly dedicated to a motor, e.g. FOC and outer ctrl
- create a dictionary that allows usage of the interfaces of the above models
- Create a simple supervisor that uses the dictionary and is able to switch between two instances of the models, either by:
     - using multiport switching and reusable functions
     - vectorizing the dictionary elements in a collection of parameters and iterate over it
- Generate code and see how the codegen behaves, trying to understand pros and cons

**Comment by mfussi66** [comment]
Taking inspiration from the above diagrams, and from the ideas laid out in the previous post, I incorporated together in a single model the Outer controller, FOC, and estimators.

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/c615b67c-cf1e-40f6-93ae-084d5ddb2c88)

Of course all the models are references to the ones already created. I also kept the dictionary intact, at the moment besides removing the linking to can_messaging.sldd and supervision.sldd .

The interfaces of the models have not been changed, in fact I was able to successfully test the controllers with the PMSM test model.

Zooming up, we would like to have the supervisor_rx layer to act as a motor manager of sorts: handling limits, control mode, and so on. It needs, however, to be instantiated for each motor, like so:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/875d24aa-e25f-4513-84c0-61f85bf07734)

The image above shows the basic architectural model of one Motor Driver, which needs to be duplicated or iterated over.
At the moment I took the liberty to sketch out a new interface for the supervision, since the can messaging part needs to be externalized. 

In any case, the supervision logic needs to run independently for each motor, and so it will need to be referenced from the motor_controller.slx.

**Comment by mfussi66** [comment]
> Zooming up, we would like to have the supervisor_rx layer to act as a motor manager of sorts: handling limits, control mode, and so on. It needs, however, to be instantiated for each motor, like so:

The supervisor_rx can be split-up in the motor-specific FSM that handles high-level events, and embed that part into the motion controller. See the picture below and #52 .

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/eff04cf2-2f3c-45b2-9ae1-038794ca9005)

The data dictionary could additionally define:
-  Formal definitions of the events in input of the FSM (maybe in an enum?): so that the input interface of the whole motion controller can be simplified and decoupled from the Message handler component, which is specific to the amcbldc
- a GlobalConfig structure that is independent of the motor, and can be passed with no discrimination.

The AMC-FOC could use a dispatcher layer to route the commands to the specific motion controllers
<details>
<summary> See here: </summary>

 ![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/8a81d3b1-9c3c-4574-9ff4-75ad5fa2f9f5)
 
</details>

The AMCBLDC could use directly the CAN message handler:

<details>
<summary> See here: </summary>

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/2c9b1748-f209-4f86-ba59-7ea993497e08)

</details>

**Comment by mfussi66** [comment]
Reference in the matlab doc regarding referenced project, for future (excuse the repetition) reference: https://www.mathworks.com/help/matlab/matlab_prog/componentize-large-projects.html

**Comment by valegagge** [comment]
Hi @mfussi66, I just want to inform you that I'm still working on this issue: https://github.com/robotology/icub-firmware-models/issues/40.

**Comment by mfussi66** [comment]
The work on the dictionary at the moment is the following:

I created an ActuatorConfiguration that at the moment includes the estimationConfiguration, which I will make global. The pids are also wrapped up in their own struct.

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/de5e93d8-1d01-425c-9803-88146e99df99)

Then, I also created a SupervisorReceivedEvents enum type, which can be:
- None
- setLimits
- setControlMode
- setTarget
- setPid

The enum can then be used in such a way:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/1edc8b89-4d92-47db-a397-c6b04d68e187)

The events are the same ones that trigger the FSM in the supervisor rx

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/54490b3a-a2a2-4164-925f-66bdccf2eb57)

**Comment by mfussi66** [comment]
Wrapping up the proposed extension so far, I'll show here the list of Buses, with the new ones expanded for clarity:

![MATLAB_XzuBM7hEUV](https://github.com/robotology/icub-firmware-models/assets/38140169/3423a23a-68d0-4fbd-9083-cf3b74d8e608)

- **ActuatorConfiguration** is intended, if it was not clear before, to be a wrapper for all parameters specific to one motor only. Creating actuator-specific configuration allows to run different types of motor on the same board easily. 
- **Flags** contains the flags that are passed around inside the motion controller. `enable_sending_message_status` was removed, as at the moment there is no `Supervisor_TX` to use. The `External Fault button flag` was kept just in the `ExternalFlags` as an input to the whole actuator component, as it was used only in `Supervisor_RX`
- **GlobalConfiguration** contains parameters that can be shared between motors, aka the `EstimationConfiguration`:
    - the $\lambda$ used to compute the Current RMS
    - the environment temperature
    - the velocity estimation mode
    To be fair, this is not exactly true as different ADCs and encoders _might_ benefit from different configurations, but moving the `EstimationConfiguration` in `ActuatorConfiguration` should be simple
- **PIDConfiguration** is a collector of the pids for each type of available control for a motor
- **SupervisorInputLimits** is intended as a data structure that replaces the `SV_Limits` in the `supervisor.sldd` dictionary: it is used as support to get the current limits and then store them in `Thresholds`
- The **supervisorReceivedEvents** are explained in the post above

-------

So, what does our Motion Controller look from the outside? Like this: 

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/16297803-fbff-45be-8d5c-aab2cf936a8d)

In green is the signal running at FOC rate (27KHz), while in blue the signals are running at standard tick rate (1KHz).
As we can see there are lots inputs, mostly caused by implementation of the supervisor.
 Just for a test, I tried to implement the `motorConfig` input as an [In Bus](https://www.mathworks.com/help/releases/R2023b/simulink/slref/inbuselement.html) port,  which is basically InPort + Bus Selector. In this way it was simple to get just the motor config structure from the actuator. I'd be curious to see how the code generation behaves with such a component, but I suspect that it is just equivalent.

**Comment by valegagge** [comment]
> > Hi @mfussi66, I just want to inform you that I'm still working on this issue: #40.
> 
> That's ok, the logic of the amcbldc, its dictionary and supervisor will not be touched.

Hi @mfussi66 ,
Unfortunately, this is not true. I need to update the dictionary by adding the `Overcurrent` field in the `Flag `struct to fix bug #58 and adding the `HwOverCurrentFlag` field in the `ExternalFalg ` struct to implement this feature #40 

Since I just started to work, I can put my work on hold and wait for your work to be completed. 
Obviously, we can catch up to see if my solutions work fine after your changes.

**Comment by valegagge** [comment]
cc @pattacini @Nicogene

**Comment by pattacini** [comment]
Hi @valegagge 

@mfussi66 is going with a completely separate branch and a brand-new dictionary, which is different from that of the AMCBLDC. So, no interaction during this development.

We decided to attack AMCFOC per se and only then update the AMCBLDC architecture to the use of the new more general system.

Of course, this would entail an extra effort to deal with the tail represented by the AMCBLDC; on the other hand, we will proceed much faster with the AMCFOC.

**Comment by mfussi66** [comment]
Next order of business is:
- [ ] Reduce the inputs in the motor supervisor by mimicking the marshaling/demarshaling logic of the amcbldc
- [ ] Create a test model for >1  new motion controllers
- [ ] Investigate how the components of the dictionary can be vectorized

**Comment by pattacini** [comment]
Hi @mfussi66 

I took the liberty to add up the fourth point:

> Push the work to the repo

In this respect, we ought to create the two infamous projects:
- One metaproject
- One amcfoc project

**Comment by mfussi66** [comment]
> * [ ]  Reduce the inputs in the motor supervisor by mimicking the marshaling/demarshaling logic of the amcbldc

Similarly to the amcbldc that uses the structure BUS_MESSAGES_RX, I created the following bus:

![MATLAB_eUwej1HEUV](https://github.com/robotology/icub-firmware-models/assets/38140169/a71ab820-43d9-4337-8975-733e3b68d1c2)

So `SupervisorReceivedEvents` becomes the data structure holding the data of the possible events that can be received. The type of event is, as always `event_type`.
`SupervisorReceivedEvents` becomes the input type for the `Events` port: 
![image](https://github.com/robotology/icub-firmware-models/assets/38140169/6af11653-0c20-45ab-a007-d10097102f46)

Inside the motor supervisor we can use the In Bus Element to route the `Events` members:

![MATLAB_GDIkCJMyBR](https://github.com/robotology/icub-firmware-models/assets/38140169/dba91b95-442d-4474-a21a-692182d7e172)

Finally, `BoardState` would require careful handling, and `receivednewsetpoint` requires changes to the supervisor logic.

**Comment by pattacini** [comment]
Well done!

**Comment by mfussi66** [comment]
> * [ ]  Create a test model for >1  new motion controllers

At the moment I was able to run a test with one motor:

https://github.com/robotology/icub-firmware-models/assets/38140169/5c328838-07c0-47a5-b525-7296452674c9

So hopefully now's it's just a matter of wrapping in FOR subsystem the controllers.

**Comment by pattacini** [comment]
Lovely!

**Comment by mfussi66** [comment]
> * [ ]  Investigate how the components of the dictionary can be vectorized in view of the AMCBLDC refactoring
> *

For this, we could script the operation by opening the dictionary file, get all the data structures that we want to vectorize, and change the `Dimensions` parameter via code. Then save the dictionary. This is because the  Architectural Data Editor does not allow changing Dimensions via variable (or constant) defined in it.

**Comment by pattacini** [comment]
Cool!

For tomorrow's review, let's focus on these points:
- [ ] Create a test model for >1  new motion controllers
- [ ] Push the work to the repo

Teh remaining points will be addressed in the next sprint.

**Comment by mfussi66** [comment]
I was able to run two instances of the motion controller, but I had to resort to model duplication.
In the picture below you can see that:
1- I send two separate targets
2- press the fault and at the same time the two controllers go in idle
3 - remove the fault and re-establish the control mode
4 - set the two controllers in idle in two separate moments
![image](https://github.com/robotology/icub-firmware-models/assets/38140169/50ea3479-70fc-427f-808f-7dae8fe9199c)

Now, there is an issue with the supervisor that might create some unintended effect, which is the `receivedNewSetpoint` which is always set to true. This was a simplification that I made to focus on the other more important things, but we can go back to handling it when we will touch the supervisor.

Anyway, my initial idea was to wrap the motion controller in a [For Each subsystem](https://it.mathworks.com/help/simulink/slref/foreachsubsystem.html). In this way I could have simply vectorized the inputs by concatenating elements, and split the outputs and send them to the motors. However, there are issues:
- The for each subsys can only be simulated in Accelerator Mode
- The accelerator mode requires compilation
- the custom c functions used in the supervisor use `rtw_enablemotors` and `rtw_disablemotors` which trigger a linking error
- And it seems that there are limitations with code generation: You cannot perform these types of code generation:
[Limitations](https://it.mathworks.com/help/simulink/ug/repeat-an-algorithm-using-a-for-each-subsystem.html#mw_76ab6d1d-3ef6-4c2e-9438-e226c070ddc0)
```
You cannot perform these types of code generation:

- Generation of a Simulink Coder™ S-function target

- Simulink Coder code generation under both of these conditions:

- - A Stateflow® or MATLAB Function block resides in the subsystem. <---- Might be our case

- - This block tries to access global data outside the subsystem, such as Data Store Memory blocks or Simulink.Signal objects of ExportedGlobal storage class.
```

I guess at some point I could try to make a simple test model to see what the actual capabilities are.

**Comment by pattacini** [comment]
Well done!

I'll open up a dedicated issue for further investigating the For-Each.
As of now, let's proceed with block duplication.

Let's complete the task by publishing the work up to the repo with 2 proper projects.

**Comment by mfussi66** [comment]
PR here: https://github.com/robotology/icub-firmware-models/pull/62
