### ISSUE TITLE
AMCFOC – Test the architecture

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-firmware-models#72]
Following up on https://github.com/robotology/icub-firmware-models/issues/60#issuecomment-1860980782, we're required to:
- restore the custom code calls
- create proper automated test to verify if all conditions turn out as expected

**Comment by mfussi66** [comment]
The test was embedded in a Test Harness inside the supervisor, with sequence and assessment, as seen here:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/f0a73a13-62e1-442d-badd-3cda5243ab02)

Simply put, the **Test Sequence** sets the inputs to the supervisor in the usual sequence, and at the end it pushes the fault button. 
The step change occurs in the sequencer after 0.01secs, and the **Test Assessment** block checks if the condition for moving to the next step is satisfied.
For example, if at the `set_mode` step the previously set PID D value does not match (`check_pid_set`), a warning is thrown.

At the moment the checks are working as expected 👍  I can add more steps to verify if the transitions work as expected.

**Comment by pattacini** [comment]
Nice!

> I can add more steps to verify if the transitions work as expected.

Ideally, we should check as many conditions and pathways as possible.

Another important point is to verify whether transitions occur in the expected amount of time without taking up longer lapses.

**Comment by mfussi66** [comment]
I started adding a scenario to check for behaviour of hardware faults, so far there is only the overcurrent:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/a2d604b5-cfc8-4ae3-9720-00b117b537bf)

And it was useful because it made me realize that I forgot to reset the flag `isInFault`, which would allow to switch back to idle when the fault condition disappeared:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/9d38b9eb-b843-40ed-b6f0-46b94c322b60)


I'm not a fan of how I'm writing the test sequences, I'm curious to see if it can be avoided to repeat the steps when evaluating them in different conditions.

**Comment by pattacini** [comment]
>I'm not a fan of how I'm writing the test sequences, I'm curious to see if it can be avoided to repeat the steps when evaluating them in different conditions.

Maybe barely related but still useful:
- https://www.mathworks.com/help/sltest/ug/using-an-external-function-in-test-sequence-block.html

**Comment by mfussi66** [comment]
> > I'm not a fan of how I'm writing the test sequences, I'm curious to see if it can be avoided to repeat the steps when evaluating them in different conditions.
> 
> Maybe barely related but still useful:
> 
>     * [mathworks.com/help/sltest/ug/using-an-external-function-in-test-sequence-block.html](https://www.mathworks.com/help/sltest/ug/using-an-external-function-in-test-sequence-block.html)

I'll give it a look!

Today I implemented new checks, related to control mode switches and bumpless switch:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/458e23c3-ebdf-4d95-a402-9de1c305f17d)

Also, I added a simple discrete linear model that simulates a RL circuit, so that it could be used as a very coarse emulation of a motor if more sophistication is needed

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/71117eb0-30d5-46ff-bc8e-b6b0bc2cf77a)

All in all the tests seem fine, but `check_mode_velocity` fails, because the output of the Supervisor occurs one sample after the input

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/60fb642b-ce55-4a15-91d0-bfe4bb637f68)

**Comment by mfussi66** [comment]
I found the culprit of the 1 sample lag above, a silly mistake:

In the input dispatcher, I was triggering the event of `SetControlMode` before storing the desired mode:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/768d3cab-3c92-4fbd-825e-5aee18a08e36)

The event triggers the transition in the Control Mode handler who then checks for `requiredControlMode`. I thought the assignment was made before letting the Control Mode handler execute, who knew!

After swapping the two instructions, we have a perfect alignment of control mode changes:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/30cb3412-3467-4d7c-887e-4777966dfb70)

**Comment by pattacini** [comment]
Nicely debugged!

Tests are indeed useful!

**Comment by mfussi66** [comment]
There was also a timing issue I found, that was caused by the `InputDispatcher`, and it was probably more critical. Basically, one FSM tick needed to occur before it could be able to process another event. 

To fix this, I replaced the subcharts in the dispatcher with graphical functions. See the picture bellow. In this way, the return occurs immediately and at the next tick the Supervisor is able to process another call.
![image](https://github.com/robotology/icub-firmware-models/assets/38140169/8b7bda63-7a58-44d3-a374-ebb198d01bca)

**Comment by mfussi66** [comment]
> Generating the static code metrics for ONE motion controller, we can see the following:

I noticed that I had a different compiler set up for the new supervisor, after setting the same one as the AMCBLDC, we have much better results:

|  | Old supervisor | New supervisor |
|--------|--------|--------|
| **Lines of code** | 1014 | 834 |
| **Global variables size (bytes)** | 664 | 0 | 
| **Accumulated stack size (bytes)** | 241 | 174 | 

I'm surprised by the zero on the global variables, maybe they are needed when many subsystems are interacting with each other.

**Comment by mfussi66** [comment]
At the moment, I'm struggling to make the simulation work properly: it seems that even in open loop the simulated pmsm cannot spin:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/dfbd5bde-69f3-43bf-99ce-3d8f1b25b86b)

I'll try to revert to a previous commit to see what changed.

**Comment by pattacini** [comment]
> At the moment, I'm struggling to make the simulation work properly: it seems that even in open loop the simulated pmsm cannot spin:

Fixed via #77.

**Comment by mfussi66** [comment]
Yep, and the new supervisor works as expected:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/4b77bf10-3028-4f91-b708-8da20b059016)

**Comment by pattacini** [comment]
Nice!

**Comment by pattacini** [comment]
Hi @mfussi66 

Just to make a recap of the task's objectives:
- <kbd>restore the custom code calls</kbd>
  Is this accomplished? 
- <kbd>create proper automated test to verify if all conditions turn out as expected</kbd>
  Lots of work done in this respect. Did you plan to extend the existing tests or can we consider this subtask complete?

**Comment by mfussi66** [comment]
> Is this accomplished?

Done ✅ 
Both for the iCubTech code replacement library and the C functions called in stateflow

>  Lots of work done in this respect. Did you plan to extend the existing tests or can we consider this subtask complete?

I think It can be considered completed, also because the integration test in simulation was successful.

**Comment by pattacini** [comment]
Fantastic job!
Closing the issue then.
